"""init_schema_russian

Revision ID: cdc71a8fc84d
Revises: 
Create Date: 2026-04-14 15:15:43.488436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdc71a8fc84d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_hash')
    )
    op.create_table('enemies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enemy_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('damage_min', sa.Integer(), nullable=False),
    sa.Column('damage_max', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('dodge_chance', sa.Integer(), nullable=False),
    sa.Column('crit_chance', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('gold_min', sa.Integer(), nullable=False),
    sa.Column('gold_max', sa.Integer(), nullable=False),
    sa.Column('loot_table', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', postgresql.ENUM('оружие', 'броня', 'аксессуар', 'расходник', 'квестовый', 'сумка', name='item_type'), nullable=False),
    sa.Column('rarity', postgresql.ENUM('обычный', 'необычный', 'редкий', 'эпический', 'легендарный', name='item_rarity'), nullable=False),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('sell_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('required_class', sa.ARRAY(postgresql.ENUM('воин', 'жрец', 'паладин', 'маг', 'призыватель', 'некромант', 'варвар', 'охотник', 'друид', 'вор', 'оборотень', name='character_class')), nullable=True),
    sa.Column('modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('damage_min', sa.Integer(), nullable=False),
    sa.Column('damage_max', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('max_durability', sa.Integer(), nullable=False),
    sa.Column('slot', postgresql.ENUM('оружие', 'броня', 'шлем', 'перчатки', 'ботинки', 'аксессуар', 'кольцо1', 'кольцо2', name='equipment_slot'), nullable=True),
    sa.Column('is_stackable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_type', postgresql.ENUM('город', 'лес', 'дорога', 'подземелье', 'пещера', 'горы', 'болото', name='location_type'), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('coord_x', sa.Integer(), nullable=False),
    sa.Column('coord_y', sa.Integer(), nullable=False),
    sa.Column('danger_level', sa.Integer(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_description_generated', sa.Boolean(), nullable=False),
    sa.Column('is_safe', sa.Boolean(), nullable=False),
    sa.Column('has_shop', sa.Boolean(), nullable=False),
    sa.Column('has_tavern', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_coords', 'locations', ['coord_x', 'coord_y'], unique=False)
    op.create_index('idx_locations_region', 'locations', ['region'], unique=False)
    op.create_index('idx_locations_type', 'locations', ['location_type'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_vk_user_id'), 'users', ['vk_user_id'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('character_class', postgresql.ENUM('воин', 'жрец', 'паладин', 'маг', 'призыватель', 'некромант', 'варвар', 'охотник', 'друид', 'вор', 'оборотень', name='character_class'), nullable=False),
    sa.Column('current_location_id', sa.UUID(), nullable=False),
    sa.Column('hp_current', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('mana_current', sa.Integer(), nullable=False),
    sa.Column('mana_max', sa.Integer(), nullable=False),
    sa.Column('stamina_current', sa.Integer(), nullable=False),
    sa.Column('stamina_max', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('жив', 'мёртв', 'отдых', name='character_status'), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('fatigue', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('inventory_slots', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fatigue BETWEEN 0 AND 100', name='characters_fatigue_range'),
    sa.CheckConstraint('gold >= 0', name='characters_gold_non_negative'),
    sa.CheckConstraint('hp_current BETWEEN 0 AND hp_max', name='characters_hp_valid'),
    sa.CheckConstraint('level BETWEEN 1 AND 15', name='characters_level_range'),
    sa.CheckConstraint('mana_current BETWEEN 0 AND mana_max', name='characters_mana_valid'),
    sa.CheckConstraint('stamina_current BETWEEN 0 AND stamina_max', name='characters_stamina_valid'),
    sa.CheckConstraint('strength > 0 AND agility > 0 AND intelligence > 0', name='characters_stats_positive'),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_characters_level', 'characters', ['level'], unique=False)
    op.create_index('idx_characters_name', 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_current_location_id'), 'characters', ['current_location_id'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_table('location_connections',
    sa.Column('from_location_id', sa.UUID(), nullable=False),
    sa.Column('to_location_id', sa.UUID(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('travel_difficulty', sa.Integer(), nullable=False),
    sa.CheckConstraint('from_location_id != to_location_id', name='no_self_connection'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_location_id', 'to_location_id')
    )
    op.create_index('idx_connections_from', 'location_connections', ['from_location_id'], unique=False)
    op.create_index('idx_connections_to', 'location_connections', ['to_location_id'], unique=False)
    op.create_table('shop_items',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.CheckConstraint('buy_price > 0 AND sell_price > 0', name='prices_positive'),
    sa.CheckConstraint('stock IS NULL OR stock >= 0', name='stock_valid'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'item_id')
    )
    op.create_index('idx_shop_location', 'shop_items', ['location_id'], unique=False)
    op.create_table('character_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', postgresql.ENUM('победа_над_боссом', 'смерть_союзника', 'важный_выбор', 'открытие', 'квест_завершён', 'повышение_уровня', 'уникальное_событие', name='memory_type'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='memory_importance_range'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memories_importance', 'character_memories', ['importance'], unique=False)
    op.create_index(op.f('ix_character_memories_character_id'), 'character_memories', ['character_id'], unique=False)
    op.create_table('character_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('активен', 'завершён', 'провален', 'отменён', name='quest_status'), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_character_quests_status', 'character_quests', ['status'], unique=False)
    op.create_index(op.f('ix_character_quests_character_id'), 'character_quests', ['character_id'], unique=False)
    op.create_table('combat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('enemy_id', sa.UUID(), nullable=True),
    sa.Column('enemy_name', sa.String(length=100), nullable=False),
    sa.Column('enemy_hp_current', sa.Integer(), nullable=False),
    sa.Column('enemy_hp_max', sa.Integer(), nullable=False),
    sa.Column('enemy_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=False),
    sa.Column('combat_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enemy_id'], ['enemies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'is_active', name='combat_unique_active')
    )
    op.create_index('idx_combat_active', 'combat_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_combat_sessions_character_id'), 'combat_sessions', ['character_id'], unique=False)
    op.create_table('game_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_logs_character', 'game_logs', ['character_id'], unique=False)
    op.create_index('idx_game_logs_component', 'game_logs', ['component'], unique=False)
    op.create_index('idx_game_logs_level', 'game_logs', ['level'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('durability IS NULL OR durability >= 0', name='inventory_durability_valid'),
    sa.CheckConstraint('quantity > 0', name='inventory_quantity_positive'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'item_id', name='unique_stackable')
    )
    op.create_index('idx_inventory_character', 'inventory', ['character_id'], unique=False)
    op.create_index(op.f('ix_inventory_character_id'), 'inventory', ['character_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_id'), 'inventory', ['item_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('награда_квест', 'награда_бой', 'покупка', 'продажа', 'отдых', 'ремонт', 'обучение', 'штраф', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount != 0', name='transactions_amount_nonzero'),
    sa.CheckConstraint('balance_after >= 0', name='transactions_balance_nonnegative'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_character_id'), 'transactions', ['character_id'], unique=False)
    op.create_table('equipment',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('slot', postgresql.ENUM('оружие', 'броня', 'шлем', 'перчатки', 'ботинки', 'аксессуар', 'кольцо1', 'кольцо2', name='equipment_slot'), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('equipped_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'slot'),
    sa.UniqueConstraint('inventory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.drop_index(op.f('ix_transactions_character_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_inventory_item_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_character_id'), table_name='inventory')
    op.drop_index('idx_inventory_character', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('idx_game_logs_level', table_name='game_logs')
    op.drop_index('idx_game_logs_component', table_name='game_logs')
    op.drop_index('idx_game_logs_character', table_name='game_logs')
    op.drop_table('game_logs')
    op.drop_index(op.f('ix_combat_sessions_character_id'), table_name='combat_sessions')
    op.drop_index('idx_combat_active', table_name='combat_sessions')
    op.drop_table('combat_sessions')
    op.drop_index(op.f('ix_character_quests_character_id'), table_name='character_quests')
    op.drop_index('idx_character_quests_status', table_name='character_quests')
    op.drop_table('character_quests')
    op.drop_index(op.f('ix_character_memories_character_id'), table_name='character_memories')
    op.drop_index('idx_memories_importance', table_name='character_memories')
    op.drop_table('character_memories')
    op.drop_index('idx_shop_location', table_name='shop_items')
    op.drop_table('shop_items')
    op.drop_index('idx_connections_to', table_name='location_connections')
    op.drop_index('idx_connections_from', table_name='location_connections')
    op.drop_table('location_connections')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_current_location_id'), table_name='characters')
    op.drop_index('idx_characters_name', table_name='characters')
    op.drop_index('idx_characters_level', table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_users_vk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('quests')
    op.drop_index('idx_locations_type', table_name='locations')
    op.drop_index('idx_locations_region', table_name='locations')
    op.drop_index('idx_locations_coords', table_name='locations')
    op.drop_table('locations')
    op.drop_table('items')
    op.drop_table('enemies')
    op.drop_table('ai_prompts')
    # ### end Alembic commands ###
